// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;
using SysVendas.Data.Context;

namespace SysVendas.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20180806180550_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("SysVendas.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Codigo");

                    b.Property<string>("Nome")
                        .HasColumnName("Nome");

                    b.HasKey("Codigo");

                    b.ToTable("FORNECEDOR");
                });
#pragma warning restore 612, 618
        }
    }
}
